### ISSUE TITLE
FileNotFoundError When Loading Pretrained Model 'avg.pt

### ISSUE THREAD

**Issue by awais2** [kwanyun/StyleSketch#2]
**Issue Description:**

**Step 1:**
I followed the instructions provided in the README to set up the project and encountered an error while attempting to run the code. Here are the steps I took:

1. Downloaded the required file, `"stylegan2-ffhq-1024x1024.pt,"` from the provided Google Drive link.
2. Copied the downloaded file to the directory `"/StyleSketch/sketch/checkpoints/stylegan_pretrain."`
3. Ran the command ```python3 generate.py --train_data model_sketch_MJ```.

However, I encountered the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/stylegan_pretrain/avg.pt'
```

**Step 2:**
In an attempt to resolve the above error, I assumed that the file `"stylegan2-ffhq-1024x1024.pt"` is equivalent to `"avg.pt,"` so I renamed it accordingly and reran the code.

Unfortunately, this led to another error:

```
RuntimeError: Error(s) in loading state_dict for SketchGenerator. The complete error log is attached in 

```
[error.txt](https://github.com/kwanyun/StyleSketch/files/15058639/error.txt)

Your attention to this matter would be greatly appreciated. Let me know if any additional information is needed. Thank you!

---

**Comment by kwanyun** [comment]
I apologize for not uploading avg.pt file which is average w+ weight for the truncation used in the StyleGAN. I have uploaded the file in the code (sketch/chekpoints/stylegan_pretrain/avg.pt)

**Comment by awais2** [comment]
@kwanyun, thank you for your prompt response. Apologies for the delay; I encountered difficulty accessing my system to conduct the test.

I've now conducted the test by re-cloning the repository and attempting to execute it. However, I encountered the following error:

```
Traceback (most recent call last):
  File "generate.py", line 95, in <module>
    generate_data(opts, args.train_data)
  File "generate.py", line 50, in generate_data
    generator.load_state_dict(checkpoint['model_state_dict'], strict=True)
  File "/home/edge/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SketchGenerator:
    Missing key(s) in state_dict: "up_512_512_0.up.1.weight", "up_512_512_0.up.2.weight", "up_512_512_0.up.2.bias", "up_512_512_0.up.2.running_mean", "up_51"

```

I've also provided a detailed error report as attachment
[error2.txt](https://github.com/kwanyun/StyleSketch/files/15147611/error2.txt)
 for your reference. Once again, thank you.

**Comment by kwanyun** [comment]
Due to the 'module' prefix added by PyTorch's DataParallel, if you are using multiple GPUs with DataParallel, you can keep this setup. However, you should detach if you are not using DataParallel with multiple GPUs. I have found some methods to detach it.
 
https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

**Comment by awais2** [comment]
I wanted to express my sincere gratitude for your prompt response and invaluable guidance. Your recommendation regarding the 'module' prefix added by PyTorch's DataParallel has been immensely helpful.

After implementing your suggestion, the code worked succesfully. However, upon further testing, I identified a potential enhancement that could further refine the code in the `generate.py` file.

Currently, the relevant line of code reads:

```python
checkpoint = torch.load(os.path.join(checkpoint_path, f'model_{name_train_style}.pth'), map_location=device)
```

Considering the command:

```bash
python generate.py --train_data model_sketch_MJ
```

I propose modifying the above code line to:

```python
checkpoint = torch.load(os.path.join(checkpoint_path, f'{name_train_style}.pth'), map_location=device)
```

This modification ensures consistency in file naming with the `name_train_style` argument provided by the user. Without this adjustment, executing the specified command would result in the creation of a file named `model_model_sketch_MJ.pth`, potentially leading to the below error.

```bash
FileNotFoundError: [Errno 2] No such file or directory: './model_dir/model_model_sketch_MJ.pth'
```

**Comment by kwanyun** [comment]
Thank you for your suggestion. I should change the command tp

`python generate.py --train_data sketch_MJ`

**Comment by bikraj2** [comment]
@awais2 How did you manage to detached the module prefix? I am stuck here forever

**Comment by kwanyun** [comment]
There are two simple ways to solve the module prefix:
1. Remove module prefix on loaded model
2. Use dataparellel while keeping the module prefix.
